# Generated by Django 4.0.3 on 2022-03-03 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measures', '0002_alter_measure_drink_alter_measure_measure_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_buyer', to=settings.AUTH_USER_MODEL)),
                ('measure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='measures.measure')),
                ('seller_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
