# Generated by Django 4.0.3 on 2022-03-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
