# Generated by Django 4.0.3 on 2022-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_buyer_id_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4),
        ),
    ]
