# Generated by Django 4.0.3 on 2022-03-03 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_alter_drink_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='drink',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='drinks.drink'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure_unit_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure_volume',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='measure',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to=settings.AUTH_USER_MODEL),
        ),
    ]
