# Generated by Django 4.0.3 on 2022-03-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0004_alter_measure_drink_alter_measure_measure_unit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='number_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
