# Generated by Django 4.0.3 on 2022-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('total_volume', models.PositiveIntegerField(default=None)),
                ('total_measures', models.PositiveIntegerField(default=None)),
                ('measures_remaining', models.PositiveIntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=None)),
                ('image', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
