# Generated by Django 4.0.3 on 2022-03-03 10:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_abv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='abv',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.9)]),
        ),
    ]
