# Generated by Django 4.0.3 on 2022-03-05 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_alter_drink_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='drinks.drink'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='offer_to_buy',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='bid',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
