# Generated by Django 4.0.3 on 2022-03-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_bid_drink_alter_bid_offer_to_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='number_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
